name: flask-fpt

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  image_name: flask-fpt

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: docker image build and push - CI part
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/${{env.image_name}}:${{github.run_number}}

    - name: SSH to instance and running script
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ec2-3-235-240-203.compute-1.amazonaws.com
        username: ubuntu
        key: ${{ secrets.AWS_SERVER_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/docker-test && bash flask-fpt.sh ${{env.image_name}} ${{github.run_number}} ${{secrets.DOCKER_USERNAME}}





    # - name: Deploying new image - CD part
    #   run: |
    #     ssh ${{ secrets.AWS_SERVER_KEY }} ubuntu@ec2-3-235-240-203.compute-1.amazonaws.com "cd /home/ubuntu/docker-test && bash flask-fpt.sh ${{env.image_name}} ${{github.run_number}} ${{ secrets.DOCKER_USERNAME }}"


