name: flask-fpt - MASTER

on: 
  push:
    branches: 
      - master

env:
  image_name: flask-fpt

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: FPT-OmarAnwar
        minimum-approvals: 1
        issue-title: "Testing deployment"
        issue-body: "Please approve or deny the deployment with yes/no"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Ms Teams notification
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        github-token: ${{ github.token }} # this will use the runner's token.
        ms-teams-webhook-uri: ${{ secrets.QA_DEPLOYMENT_MS_TEAMS_WEBHOOK }}
        notification-summary: Pipeline completed with status ${{ needs.build.result }} 
        notification-color: 17a2b8
        timezone: Asia/Karachi



    # - name: docker image build and push - CI part
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{secrets.DOCKER_USERNAME}}/${{env.image_name}}:${{github.run_number}}

    # - name: SSH to instance and running script
    #   uses: appleboy/ssh-action@v0.1.8
    #   with:
    #     host: ec2-3-235-240-203.compute-1.amazonaws.com
    #     username: ubuntu
    #     key: ${{ secrets.AWS_SERVER_KEY }}
    #     port: 22
    #     script: |
    #       cd /home/ubuntu/docker-test && bash flask-fpt.sh ${{env.image_name}} ${{github.run_number}} ${{secrets.DOCKER_USERNAME}}

    # - name: manual approval
    #   uses: trstringer/manual-approval@v1
    #   with:
    #     secret: ${{ secrets.GITHUB_TOKEN }}
    #     # secret: ${{ github.TOKEN }}
    #     approvers: omaranwarorbispay
    #     minimum-approvals: 1
    #     issue-title: "Deploying ${{env.image_name}}:${{github.run_number}}"
    #     issue-body: "Please approve or deny the deployment"
    #     exclude-workflow-initiator-as-approver: false
    #     additional-approved-words: ''
    #     additional-denied-words: ''



    # - name: Deploying new image - CD part
    #   run: |
    #     ssh ${{ secrets.AWS_SERVER_KEY }} ubuntu@ec2-3-235-240-203.compute-1.amazonaws.com "cd /home/ubuntu/docker-test && bash flask-fpt.sh ${{env.image_name}} ${{github.run_number}} ${{ secrets.DOCKER_USERNAME }}"


